### ISSUE TITLE
Minor build issues in Ubuntu 14.04.4 LTS CUDA 7.5  GTX 660 can be worked around so it runs

### ISSUE THREAD

**Issue by normandrobert** [ttsiodras/renderer-cuda#3]
1) configure does not find cuda in /usr/local/cuda which seems to be where apt-get from Nvdia installs it now. So the CUDA configure location directive is needed:
./configure --with-cudaSDK=/usr/local/cuda
Found an error in problem description below... restated in later comment
2) Makefile assumes that cuda libs are in $CUDA_ROOT/lib64
but in CUDA 7.5 it is $CUDA_ROOT/lib
*** Fixed easily by adding soft link
Performance: 16.7 fr/s  with GTX660 Thank you

**Comment by ttsiodras** [comment]
> Thank you

You're welcome, Normand. The 1st step you took is part of the normal process - the CUDA SDK can be installed anywhere, so I added the --with-cudaSDK option to my autoconf's "configure.ac" to allow building with an SDK installed anywhere on your machine's filesystems. 

The 2nd step seems troubling, though - you can check my configure.ac and my Makefile.am and you will see that I have not hardcoded anything to "lib64" ; in fact, if you use --with-cudaSDK...

if test "x$with_cudaSDK" != x; then
  CUDA_CFLAGS="-I$with_cudaSDK/include"
  CUDA_LIBS="-L$with_cudaSDK/lib -lcudart"
  NVCC="$with_cudaSDK/bin/nvcc"

...so the linker error you reported seems strange - by default, the link flags I use (as you can see above) point to $with_cudaSDK/lib.

**Comment by normandrobert** [comment]
Revising my bash history I have found that I described the problem incorrectly above. The problem is the other way around..  in CUDA 7.5 the library is accessible via a logical link  
ls -ltr /usr/local/cuda/lib64
lrwxrwxrwx 1 root root 24 Aug 15  2015 /usr/local/cuda/lib64 -> targets/x86_64-linux/lib

I had to add another logical link (notice recent date stamp)
ls -ltr /usr/local/cuda/lib
lrwxrwxrwx 1 root root 24 Apr  4 15:22 /usr/local/cuda/lib -> targets/x86_64-linux/lib

Sorry about the confusion

**Comment by ttsiodras** [comment]
Understood - I need to modify my `configure.ac` to detect if the platform is a 64bit one, and if so, use `CUDA_LIBS="-L$with_cudaSDK/lib64 -lcudart"` (instead of `CUDA_LIBS="-L$with_cudaSDK/lib -lcudart"`).

**Comment by normandrobert** [comment]
Looks like it. I will pull after you make changes, remove my hack and build again.

**Comment by ttsiodras** [comment]
Can you test building from the _cuda_64bit_and_some_default_locations_ branch that I just pushed? 

I am attempting to detect 64bit builds, and also adapt to two common CUDA SDK locations (under /usr/local/cuda and under /opt/cuda).

**Comment by normandrobert** [comment]
it clone https://github.com/ttsiodras/renderer-cuda.git; cd renderer-cuda;
./configure

**Comment by normandrobert** [comment]
No change in behaviour
git clone https://github.com/ttsiodras/renderer-cuda.git; cd renderer-cuda; 
./configure ..... ...... .....
configure: error: Sorry, CUDA SDK appears to be missing

Note that /usr/local/cuda is a logical link not a directory may affect your test..
robert@kalymnos:~/Code/renderer-cuda$ ls -l /usr/local/cuda
lrwxrwxrwx 1 root root 8 Jan 15 14:18 /usr/local/cuda -> cuda-7.5

# Happy below 
./configure --with-cudaSDK=/usr/local/cuda
# No happy
make ... ...
/usr/bin/ld: cannot find -lcudart

**Comment by ttsiodras** [comment]
You forgot to switch to the _cuda_64bit_and_some_default_locations_ branch - you need to...

    git clone https://github.com/ttsiodras/renderer-cuda.git
    cd renderer-cuda
    git checkout cuda_64bit_and_some_default_locations
    ./configure
    make

If my changes work, I will then merge this branch in the master, so

**Comment by ttsiodras** [comment]
I also just added a check for a symlink version of `/usr/local/cuda` - after you've switched to the test branch (`git checkout cuda_64bit_and_some_default_locations`) you can just `git pull` to fetch this latest fix.

**Comment by normandrobert** [comment]
Success! Thank you!: configure finds CUDA, make builds with some warnings. Code runs! I see a chou-chou train now.
I did a sudo apt-get -y autoremove this morning which removed some pkgs. I am not sure if this is why I needed to install a specific version automake (1.11) to build the test branch code...

robert@kalymnos:~/Code/$ git clone https://github.com/ttsiodras/renderer-cuda.git; cd renderer-cuda;
robert@kalymnos:~/Code/renderer-cuda$ git checkout cuda_64bit_and_some_default_locations; 
robert@kalymnos:~/Code/renderer-cuda$ git branch
* cuda_64bit_and_some_default_locations
  master
robert@kalymnos:~/Code/renderer-cuda$ ./configure; make;
robert@kalymnos:~/Code/renderer-cuda$
robert@kalymnos:~/Code/renderer-cuda$ ./src/cudaRenderer  ./3D-objects/trainColor.ply
